INFO:root:So should this
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4000
DEBUG:urllib3.connectionpool:http://localhost:4000 "POST /jsonrpc HTTP/1.1" 200 57
INFO:root:finish calling the rpc server
INFO:werkzeug:127.0.0.1 - - [03/Mar/2022 12:25:06] "[37mGET /getAllDataJSONRPC HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:So should this
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:22:21] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:08] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:12] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:19] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:19] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:19] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:20] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:20] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:20] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:20] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:21] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:21] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:21] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:21] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:21] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:22] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:22] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:22] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:22] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:22] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:23] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:23] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:23] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:23] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:24] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:24] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:24] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:26] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:26] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:27] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
INFO:root:So should this
INFO:root:finish calling the rpc server
ERROR:flaskserver:Exception on /getQty [GET]
Traceback (most recent call last):
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylan\OneDrive\Desktop\XML WebServices\Assignment 1\flaskserver.py", line 100, in getqty
    return jsonify(buffer + '' + totalQty)
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [10/Mar/2022 11:23:27] "[1m[35mGET /getQty HTTP/1.1[0m" 500 -
